
Lmod is automatically replacing "intel/2020.1.217" with "gcc/9.3.0".


Due to MODULEPATH changes, the following have been reloaded:
  1) mii/1.1.2

The following have been reloaded with a version change:
  1) StdEnv/2023 => StdEnv/2020
  2) flexiblascore/.3.3.1 => flexiblascore/.3.0.4
  3) gcc/12.3 => gcc/9.3.0
  4) gcccore/.12.3 => gcccore/.9.3.0
  5) gentoo/2023 => gentoo/2020
  6) imkl/2023.2.0 => imkl/2020.1.217
  7) java/17.0.6 => java/13.0.2
  8) libfabric/1.18.0 => libfabric/1.10.1
  9) openmpi/4.1.5 => openmpi/4.0.3
 10) r/4.4.0 => r/4.3.1
 11) ucx/1.14.1 => ucx/1.8.0

slurmstepd: error: *** JOB 7150501 ON cac140 CANCELLED AT 2024-11-10T08:10:31 ***
