#!/bin/bash
#SBATCH --ntasks=1
#SBATCH	--cpus-per-task=4
#SBATCH --nodes=1
#SBATCH --time=00:59:59
#SBATCH --job-name=ML
#SBATCH --account=rrg-belandl1
#SBATCH --output=grain
#SBATCH --mem-per-cpu=8G
export OMP_NUM_THREADS=1

cd $SLURM_SUBMIT_DIR

module load             StdEnv/2020  gcc/9.3.0  openmpi/4.0.3
module load             quantumespresso/6.6

mpirun --oversubscribe -np 4 pw.x < relax.in > relax.out1
